#!/bin/sh
# venv
# Quick hack: autocomplete Sublime projects

# Install:
# 1. write this file as ~/.proj
#
# 2. add your projects dir in ~/.bash_profile:
#     export SUBLIME_PROJECTS_DIR='/my/dir'
#
# 3. source ~/.proj in ~/.bash_profile:
#     source ~/.venv

VERSION="1.0"
SUBLIME=`which subl`


proj() {
    if [ "${1}" = "" ] && [ -f ".proj" ]; then
        PROJECT=`cat .proj`
    else
        PROJECT=$1
    fi

    if [ "${PROJECT}" = "" ]; then
        echo "Missing project name!"
        return 1
    fi

    $SUBLIME --project "$SUBLIME_PROJECTS_DIR/${PROJECT}.sublime-project"
}


# Autocomplete
_complete_proj() {
    local cur

    # List projects
    PROJECTS=`\
        find "$SUBLIME_PROJECTS_DIR" \
        -type f -name '*.sublime-project' \
        -exec sh -c 'basename "${0%.sublime-project}"' '{}' \;`

    # Autocomplete reply
    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}

    if [ "$1" = "proj" ] && [ "$3" = "proj" ]; then
        COMPREPLY=( $( compgen -W '$PROJECTS' -- $cur ) )
    fi

    return
}

complete -F _complete_proj proj
